<?php
/**
 * Created by PhpStorm.
 * User: Yassine
 * Date: 3/14/2020
 * Time: 1:40 PM
 */

namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use ColiBundle\Interfaces\UserInterface as ColiUserInterface;


use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser implements ColiUserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }


}